### ISSUE TITLE
Failed to open file: template.dat

### ISSUE THREAD

**Issue by ccrescent** [QW-Group/mvdparser#15]
hello,
i used : cmake to bulid the binary,
when i run :./mvdparser -f /home/gin/gin_y70/video/2017/11/22/000.mvd,it show that:

Failed to open file: template.dat
Error! Output templates parsing: Failed to read from file template.dat
Failed to load template file.
and it quit

**Comment by tcsabina** [comment]
Hi @ccrescent,

Sorry for the late reply.

The mentioned `template.dat` file is in the `src` directory of the project. Please copy it next to your mvdparser binary, which is the `build` directory in this project.
After that there will be another file copy necessary. A file called `fragfile.dat` has to be copied also from the `src` directory of the project next to the mvdparser binary.
After that it should parse the demo correctly.

regards,
toma

**Comment by ccrescent** [comment]
it works ,thank you
