### ISSUE TITLE
Windows build doesn't work

### ISSUE THREAD

**Issue by eb** [QW-Group/mvdparser#26]
When you analyze a demo on Windows, the resulting filenames lack the basename.
E.g. `-map.log` instead of `test.mvd-map.log`.
They are also empty in the sense that all the JSON data is on their default value.

**Comment by SKULK3R** [comment]
Hi, if interested you can checkout https://github.com/SKULK3R/mvdparser/releases/download/1.00/mvdparser-win32_64-1.00.zip
and the repo. It works.

**Comment by tcsabina** [comment]
Fixed with PR #30
